List<String> egyptianGovernorates = [
  'القاهرة',
  'الجيزة',
  'الإسكندرية',
  'الدقهلية',
  'البحر الأحمر',
  'البحيرة',
  'الفيوم',
  'الغربية',
  'الإسماعيلية',
  'المنوفية',
  'المنيا',
  'القليوبية',
  'الوادي الجديد',
  'السويس',
  'أسوان',
  'أسيوط',
  'بني سويف',
  'بورسعيد',
  'دمياط',
  'الشرقية',
  'جنوب سيناء',
  'كفر الشيخ',
  'مطروح',
  'الأقصر',
  'قنا',
  'شمال سيناء',
  'سوهاج'
];
List<String> arabAndMuslimCountries = [
  // Arab countries
  "Saudi Arabia",
  "United Arab Emirates",
  "Qatar",
  "Bahrain",
  "Kuwait",
  "Oman",
  "Yemen",
  "Jordan",
  "Iraq",
  "Syria",
  "Lebanon",
  "Palestine",
  "Egypt",
  "Libya",
  "Tunisia",
  "Algeria",
  "Morocco",
  "Mauritania",
  "Somalia",
  "Sudan",
  "Comoros",
  "Djibouti",
  "Turkey",
  "Iran",
  "Pakistan",
  "Afghanistan",
  "Bangladesh",
  "Indonesia",
  "Malaysia",
  "Maldives",
  "Brunei",
  "Albania",
  "Bosnia and Herzegovina",
  "Kazakhstan",
  "Uzbekistan",
  "Turkmenistan",
  "Tajikistan",
  "Kyrgyzstan",
  "Azerbaijan",
  "Senegal",
  "Mali",
  "Niger",
  "Chad",
  "Nigeria",
  "Gambia",
  "Guinea",
  "Sierra Leone",
  "Burkina Faso",
  "Ivory Coast",
  "Guinea-Bissau"
];
