List<String> egyptianGovernoratesEnglish = [
  "Cairo",
  "Giza",
  "Alexandria",
  "Dakahlia",
  "Red Sea",
  "Beheira",
  "Fayoum",
  "Gharbia",
  "Ismailia",
  "Monufia",
  "Minya",
  "Qalyubia",
  "New Valley",
  "Sharqia",
  "Suez",
  "Aswan",
  "Assiut",
  "Beni Suef",
  "Port Said",
  "Damietta",
  "South Sinai",
  "Kafr El Sheikh",
  "Matrouh",
  "Luxor",
  "Qena",
  "North Sinai",
  "Sohag"
];
List<String> arabAndMuslimCountries = [
  // Arab countries
  "Saudi Arabia",
  "United Arab Emirates",
  "Qatar",
  "Bahrain",
  "Kuwait",
  "Oman",
  "Yemen",
  "Jordan",
  "Iraq",
  "Syria",
  "Lebanon",
  "Palestine",
  "Egypt",
  "Libya",
  "Tunisia",
  "Algeria",
  "Morocco",
  "Mauritania",
  "Somalia",
  "Sudan",
  "Comoros",
  "Djibouti",
  "Turkey",
  "Iran",
  "Pakistan",
  "Afghanistan",
  "Bangladesh",
  "Indonesia",
  "Malaysia",
  "Maldives",
  "Brunei",
  "Albania",
  "Bosnia and Herzegovina",
  "Kazakhstan",
  "Uzbekistan",
  "Turkmenistan",
  "Tajikistan",
  "Kyrgyzstan",
  "Azerbaijan",
  "Senegal",
  "Mali",
  "Niger",
  "Chad",
  "Nigeria",
  "Gambia",
  "Guinea",
  "Sierra Leone",
  "Burkina Faso",
  "Ivory Coast",
  "Guinea-Bissau"
];
